### ISSUE TITLE
thanks for using deeplake, let us know if you have any issues - need for deeplake api token

### ISSUE THREAD

**Issue by mikayelh** [bigsky77/khafre#1]
hey @bigsky77. one of the authors of the blogpost - so cool to see you working on this. please let me know if you hit any snag with deeplake in Github issues or [Deep Lake community](https://hubdb.slack.com/ssb/redirect). 

We're currently working on enabling Deep Lake environment token, will update you soon on this.

Warmly,
mikayelh

**Comment by bigsky77** [comment]
Hi @mikayelh -  I'm enjoying working with Deep Lake so far.  I'll reach out if I hit any issues!

**Comment by mikayelh** [comment]
great to hear - perfect! :)

**Comment by mikayelh** [comment]
hey @bigsky77 , [here's the updated Twitter notebook on how to use deeplake with API token as environmental var](https://colab.research.google.com/drive/1CTCUHLIyJS5I_cbn356L5rULvVIwX_zZ?usp=sharing) 
 
 Perhaps you might want to update the Readme to clarify that.

**Comment by bigsky77** [comment]
updated - should be good now

**Comment by istranic** [comment]
Hey @bigsky77. I'm on the Activeloop team and I'd love to learn more about your experience with Deep Lake. We're also launching many new features and your input would be very valuable. Are you available to jump on a 30-min call early next week?

**Comment by bigsky77** [comment]
Hey @istranic!  I’ve been enjoying Deep Lake so far.  If you can shoot me a dm on TG @bigsky7 Id love to schedule some time to chat.
